name: Build and Push Python Image into GCP

on:
    push:
        branches: [main]
jobs:
    deploy:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        env: 
            IMAGE_NAME: bigdata
            PROJECT_ID: bigdata-412310
        steps:
        -   name: Checkout
            uses: actions/checkout@v4

        -   id: 'auth'
            name: 'Authenticate to Google Cloud'
            uses: 'google-github-actions/auth@v2'
            with:
                credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

        -   uses: google-github-actions/setup-gcloud@v2
            with:
                project_id: ${{ env.PROJECT_ID}}
        -   name: 'Create env file'
            run: |
              echo "${{ secrets.ENV_FILE }}" > .env

        -   name: 'Set up Cloud SDK'
            uses: 'google-github-actions/setup-gcloud@v1'
            
        -   name: Build and Push the docker image
            run: |
                gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet
                docker buildx build --platform linux/amd64 -t europe-west3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest --build-arg DEV_MODE=False .
                docker push europe-west3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
                gcloud run services update app --image europe-west3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest --region europe-west3
        