---
name: Build and Push Python Image into GCP
on:
    push:
        branches: [main]
jobs:
    build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        env: 
            IMAGE_NAME: bigdata
            PROJECT_ID: bigdata-412310
        steps:
        -   name: Checkout
            uses: actions/checkout@v3

        -   id: 'auth'
            name: 'Authenticate to Google Cloud'
            uses: 'google-github-actions/auth@v2'
            with:
                credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}


        -   uses: google-github-actions/setup-gcloud@v2
            with:
                service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY}}
                project_id: ${{ env.PROJECT_ID}}
                export_default_credentials: true
                
        -   name: Build Docker Image
            run: docker build -t $IMAGE_NAME:latest .

        -   name: Configure Docker Client
            run: |-
                gcloud auth configure-docker --quiet
                gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

        -   name: Push Docker Image to Container Registry (GCR)
            run: |-
                    docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
                    docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
                    
        -   name: Push Docker Image to Artifact Registry
            run: |-
                    docker tag $IMAGE_NAME:latest europe-west3-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
                    docker push europe-west3-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest